AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ModelName:
    Description: Model name
    Type: String
  ModelDataUrl:
    Description: Location of model artifact
    Type: String
  TrainingImage:
    Description: The container used to train the model
    Type: String
  InstanceType:
    Description: Instance type
    Type: String
    Default: ml.t2.medium
  InstanceCount:
    Description: Instance count
    Type: String
    Default: 1
  RoleArn:
    Description: Execution Role ARN
    Type: String
  Environment:
    Description: Environment
    Type: String

Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties: 
      Containers: 
        - 
         Image: !Ref TrainingImage
         ModelDataUrl: !Ref ModelDataUrl
         Environment: {"SAGEMAKER_ENABLE_CLOUDWATCH_METRICS": "true", "SAGEMAKER_PROGRAM":"train_and_deploy.py", "SAGEMAKER_SUBMIT_DIRECTORY":"s3://sagemaker-us-east-1-980714697697/sagemaker-scikit-learn-2020-10-19-15-55-56-882/source/sourcedir.tar.gz"}
      ExecutionRoleArn: !Ref RoleArn
      ModelName: 
        Fn::Join:
          - ""
          - - !Ref ModelName
            - "-"
            - !Ref Environment
 
  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties: 
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      EndpointName: 
        Fn::Join:
          - ""
          - - "scikit-byo-"
            - !Ref Environment
 
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants: 
        -
          ModelName: !GetAtt Model.ModelName
          VariantName: variant-1
          InitialInstanceCount: !Ref InstanceCount
          InstanceType: !Ref InstanceType
          InitialVariantWeight: 1.0

 
Outputs:
  EndpointId:
    Value: !Ref Endpoint
  EndpointName:
    Value: !GetAtt Endpoint.EndpointName
